name: StyleCanvasAI

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - opencv
  - pillow
  - scikit-image
  - tqdm
  - natsort
  - ultralytics
  - einops
  - flask
  - fastapi
  - dlib
  - lmdb
  - cudatoolkit=11.7
  - cudnn=9.2.1.18
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pip:
      - basicsr
      - realesrgan
      - uvicorn
      - dill
