name: Pix2PixTester

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - opencv
  - pillow
  - scikit-image
  - torchaudio
  - torchvision
  - tqdm
  - natsort
  - ultralytics
  - einops
  - flask
  - fastapi
  - dlib
  - lmdb
  - pip
  - einops
  - pip:
      - basicsr
      - realesrgan
      - uvicorn
