name: StyleCanvasAI

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - opencv
  - pillow
  - scikit-image
  - tqdm
  - natsort
  - ultralytics
  - einops
  - flask
  - fastapi
  - dlib
  - lmdb
  - torchvision<0.17.0
  - pip
  - pip:
      - basicsr
      - realesrgan
      - uvicorn